### PR TITLE
fix: support symlinks without real paths with relative paths enabled

### LINKED ISSUE #113: `withSymlinks` doesn't work properly with relative paths on when the symlink is at the top level
the following code behaves differently when you add `.withRelativePaths()` and a symlink is at the top level. it looks like it just ignores symlinks completely

```js
const b = await new fdir()
  .withSymlinks()
  .exclude(p => p.includes('.git') || p.includes('node_modules'))
  .crawl(process.cwd())
  .withPromise();

b.map(p => console.log(p));
```

however it works if you crawl `path.join(process.cwd(), '..')`. using `resolvePaths: false` as an argument for `withSymlinks` doesn't solve the issue either

it works perfectly without `.withRelativePaths()`

### PR DESCRIPTION
**Pull request by SuperchupuDev**
fixes #113

when investigating, i found out that the issue was caused by the following line:

https://github.com/thecodrr/fdir/blob/5a0aab5b3e108eaf677e0e39c22ff1ea03cd1a59/src/api/walker.ts#L120-L121

with relative paths on, `path` won't be an absolute path, and as such will be resolved in the `stat` call as a path relative to `process.cwd()`. this makes it throw an `ENOENT` error (unless the symlink happens to be located in `process.cwd()`). i fixed this by changing the declaration to make it an absolute path instead.

just fixing this line wasn't enough though, because the `resolvedPath` seems to always be absolute. to fix this, i did a substring transformation to a relative path (if the symlink is a file) if the `relativePaths` option is enabled and `useRealPaths` is `false`. the latter is because symlinks can point anywhere in the filesystem, so it should return an absolute path when that is the case.

directory symlinks with real paths sadly still do not work with `relativePaths` on. my plan was to make it return those as absolute paths, but that is impossible as the `joinPath` function is already built as the relative path implementation

since symlinks with real paths and relative paths still behave inconsistently before and after this pr, i marked in the docs that resolving symlinks with real paths is only supported if the `resolveSymlinks` argument is set to `false`

also, while working on this i found (and fixed) another bug, it looks like file symlinks were never normalized, and as such could have the wrong path separator etc. fixed this by moving the `normalizePath` call before the `stat.isDirectory()` check

### CODE REVIEW

**Comment by SuperchupuDev** [comment]
hi @thecodrr any chance you can take a look at this and #115 anytime soon? tinyglobby support for symlinks depends on it

File: src/api/walker.ts [hunk 1]
```diff
@@ -117,14 +117,20 @@ export class Walker<TOutput extends Output> {
         if (exclude && exclude(entry.name, path)) continue;
         this.walkDirectory(this.state, path, depth - 1, this.walk);
       } else if (entry.isSymbolicLink() && resolveSymlinks) {
-        let path = this.joinPath(entry.name, directoryPath);
+        let path = directoryPath + entry.name;
```
Comment (thecodrr) [inline src/api/walker.ts:120]: Use `joinPath.joinPathWithBasePath` instead.

Note: the test starts passing by making just this change so the test is not covering everything else. Mind taking a look at that?

File: src/api/walker.ts [hunk 2]
```diff
@@ -117,14 +117,20 @@ export class Walker<TOutput extends Output> {
...
         this.resolveSymlink!(path, this.state, (stat, resolvedPath) => {
+          resolvedPath = this.normalizePath(resolvedPath);
```
Comment (thecodrr) [inline src/api/walker.ts:122]: No need for this. `normalizePath` is only required on directory paths.

File: src/api/walker.ts [hunk 3]
```diff
@@ -117,14 +117,20 @@ export class Walker<TOutput extends Output> {
...
             if (exclude && exclude(entry.name, resolvedPath)) return;
-
             this.walkDirectory(this.state, resolvedPath, depth - 1, this.walk);
           } else {
+            if (!this.state.options.useRealPaths && this.state.options.relativePaths) {
+              resolvedPath = resolvedPath.substring(this.root.length, resolvedPath.length - 1);
+            } else {
+              // resolvedPath has a trailing slash due to the normalizePath call
+              resolvedPath = resolvedPath.substring(0, resolvedPath.length - 1)
+            }
```
Comment (thecodrr) [inline src/api/walker.ts:133]: This can be simplified to:

```ts
            const filename = basename(resolvedPath);
            const directoryPath = this.normalizePath(dirname(resolvedPath));
            resolvedPath = this.joinPath(filename, directoryPath);
```

File: documentation.md [hunk 4]
```diff
@@ -104,7 +104,7 @@ const crawler = new fdir().withDirs();
 
 ### `withSymlinks({ resolvePaths: boolean })`
 
-Use this to follow all symlinks recursively.
+Use this to follow all symlinks recursively. Not available with relative paths on unless the parameter is set to `false`.
```
Comment (thecodrr) [inline documentation.md:107]: I will have to take a deep look into this and see if there's a way around.

File: __tests__/fdir.test.ts [hunk 5]
```diff
@@ -327,6 +327,25 @@ for (const type of apiTypes) {
     mock.restore();
   });
 
+  test(`[${type}] crawl all files and include resolved symlinks without real paths with relative paths on`, async (t) => {
```
Comment (thecodrr) [inline __tests__/fdir.test.ts:330]: This test isn't covering all the changes.

**Review by thecodrr — CHANGES_REQUESTED** [review]

File: src/api/walker.ts (hunk 1 above)
Comment (SuperchupuDev) [reply src/api/walker.ts:120]: `joinPathWithBasePath` isn't exported, i'll have to export it to be able to use it

File: documentation.md (hunk 4 above)
Comment (SuperchupuDev) [reply documentation.md:107]: i don't think it's possible to have it available with realpaths as realpaths can point to anywhere outside the root, unless you add a loop to add the necessary `../`s and rework the relative path system, which sounds really complex to do

File: src/api/walker.ts (hunk 1 above)
Comment (SuperchupuDev) [reply src/api/walker.ts]: > Note: the test starts passing by making just this change so the test is not covering everything else. Mind taking a look at that?

that change on it's own fixed dir symlinks but not file symlinks, just updated the tests to also check for file symlinks

**Review by thecodrr — APPROVED** [review]
