### PR TITLE
Ensure callback is called only once

### LINKED ISSUE #143: `withPromise` promise is resolved multiple times which causes hangs on windows
```ts
const api = new fdir({
  pathSeparator: '/',
  relativePaths: true,
  resolveSymlinks: true,
  maxDepth: 0
}).crawl('/');

const paths = await api.withPromise();
console.log(paths);
```

on linux, this does resolve (but is broken as you'll learn below).
on windows (with `crawl('C:/')`), it never resolves (and is still broken the same way).

i suspect this is because our promise resolution logic is really broken.

we have a callback here:
https://github.com/thecodrr/fdir/blob/22cc385f065bd229c0e4c608b7549f4c9549bb40/src/api/async.ts#L10-L11

this callback is called when we `state.dequeue` on an empty queue (it is the on empty callback).

**it should be called one time**, since we should only call `resolve` once with the end result.

however, when we call `walkDirectory` here:
https://github.com/thecodrr/fdir/blob/22cc385f065bd229c0e4c608b7549f4c9549bb40/src/api/walker.ts#L115

`depth - 1` will be `-1` since we're currently at `0`.

`walkDirectory` will then `dequeue`:
https://github.com/thecodrr/fdir/blob/22cc385f065bd229c0e4c608b7549f4c9549bb40/src/api/functions/walk-directory.ts#L21

this `dequeue` will result in calling our callback, and therefore calling `resolve`.

but you will have seen earlier, the call to `walkDirectory` is in a loop:
https://github.com/thecodrr/fdir/blob/22cc385f065bd229c0e4c608b7549f4c9549bb40/src/api/walker.ts#L99

this means **we call `resolve` many times**.

this may not be the cause of the windows hang we see, but it is broken logic either way.

not entirely sure how to fix this, i think you are going to have to do it @thecodrr . but its highly likely its the cause of most of the hanging we've seen

### PR DESCRIPTION
**Pull request by thecodrr**
Fixes #143 

This PR fixes multiple issues with the `queue/enqueue` logic ensuring:

- `onQueueEmpty` is called only once
- The crawler aborts on error (before it kept crawling which was pointless)

Another change I had to make was how the crawler always returned results `maxDepth + 1` deep. This might break some things (but not really sure since all tests pass).

cc @SuperchupuDev can you test this out with `tinyglobby` and let me know if something breaks?

### CODE REVIEW

File: src/api/walker.ts [hunk 1]
```diff
@@ -88,13 +90,16 @@ export class Walker<TOutput extends Output> {
...
 
-    if ((signal && signal.aborted) || (maxFiles && paths.length > maxFiles))
+    if (
+      controller.signal.aborted ||
+      (signal && signal.aborted) ||
+      (maxFiles && paths.length > maxFiles)
+    )
       return;
 
-    this.pushDirectory(directoryPath, paths, filters);
```
Comment (43081j) [inline src/api/walker.ts:96]: does this change mean the root directory isn't pushed anymore? presumably `directoryPath` can be `/`, so this change would mean we push the child directories but not `/` itself.

that may be right, just checking i understand the logic if anything

**Comment by 43081j** [comment]
looks good to me!

it may be worth adding a test for `crawl("/")` and `maxDepth: 0` since thats what uncovered some of this in the first place

pretty sure we already test maxDepth elsewhere, just not at the root

**Comment by SuperchupuDev** [comment]
hey @thecodrr, it turns out this does break tests related to `maxDepth`, sorry for not finding out earlier :sweat_smile:. thankfully, it's really easy to fix! i've opened a pr at #149
